# Generated by Django 4.1.5 on 2023-03-16 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datepub', models.DateTimeField(default=datetime.datetime(2023, 3, 16, 20, 45, 49, 493536))),
                ('text', models.TextField(verbose_name='Text')),
                ('favorite', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blog',
            },
        ),
    ]
