# Generated by Django 4.1.5 on 2023-03-16 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.TextField(default='Без названия', verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='datepub',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 16, 20, 52, 49, 964544)),
        ),
    ]
